### PR TITLE
Updates derivative action for Flysystem

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Part of https://github.com/Islandora-CLAW/CLAW/issues/769

* https://github.com/Islandora-CLAW/islandora/pull/92

# What does this Pull Request do?

Adds new form elements to the action for generating derivatives.  You can now tell Alpaca what filesystem you want the derivaties sent to.  You can also use tokens to dictate the path and extension of the new file.

# What's new?
Some new form elements whose values get saved upon submit.

# How should this be tested?

Test as part of https://github.com/Islandora-CLAW/islandora/pull/92

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Review by seth-shaw-unlv — APPROVED** [review]
Works for me.

**Comment by seth-shaw-unlv** [comment]
More Travis grumpiness over 5.6

**Comment by whikloj** [comment]
@dannylamb actual whitespace standards violations in here.

**Comment by whikloj** [comment]
https://travis-ci.org/Islandora-CLAW/islandora_image/jobs/409080151#L852

**Pull request merged**
